__PyTorch for Deep Learning in 2023: Zero To Mastery (Udemy) kaynağından çalışırken alınan notlardır.__

## PyTorch Nedir?

Popüler açık kaynak derin öğrenme / makine öğrenmesi çatısıdır (framework). GPU üzerinde çalışabilecek Python ile yazılmış derin öğrenme uygulamaları çalıştırabiliriz. Tesla, Microsoft, OpenAI gibi şirketler kullanır. 

## PyTorch Neden  Kullanılır?

Makine öğrenmesinin gücünden yararlanarak çok zor problemleri çözebilecek imkanı sağlar. Robotik, tarım, sağlık vb. birçok alanda PyTorch kullanılabilir. Bilgisayar görü, doğal dil işleme vb. birçok yaklaşım üzerinde çözüm sağlar. 

## GPU (Grafik İşlem Birimi) ve TPU (Tensör İşlem Birimi)

Yüksek işlem gücü isteyen derin öğrenme algoritmalarını GPU üzerinde çalıştırabiliriz. Burada NVIDIA tarafından sağlanan CUDA kullanılır.

TPU ise GPU'dan farklı olarak makine öğrenmesine özel amaçla geliştirilmiş bir yapıdır.

## Tensör Nedir?

Daha önceden bahsettiğimiz gibi sinir ağlarına çok çeşitli (görüntü, metin, ses vb.) veriler kendi hali ile değil nümerik halinde verilirler. Bu şekilde sinir ağlarının verileri sayısal giriş olarak aldığı ve yine sonucunda sonuç olarak ürettiği sayısal yapılara tensör denir. Tensörler vektör, matris vb. yapıda olabilirler.  

## Çalışma Akışı

1. Temel PyTorch bilgisi ve temelleri (tensör ve tensör operasyonları.)
2. Veri ön işleme (Tensörler üzerinde veriler.)
3. Önceden eğitilmiş derin öğrenme modellerini kullanma.
4. Veri ile model uydurma (fitting) (Örüntüleri öğrenme - learning patterns.)
5. Öğrenilen örüntüleri kullanarak bir model ile tahmin üretme.
6. Model tahminlerini değerlendirme (evaluating).
7. Modelleri kaydetme ve yükleme.
8. Özel (custom) veri üzerinde eğitilmiş bir model kullanarak tahmin yapma. 

## PyTorch Çalışma Akışı

1. Verileri hazırla (Tensörler ile ifade et.)
2. Önceden eğitilmiş bir model oluşturma veya seçme (build or pick.)
    2.1 Bir kayıp fonksiyonu (loss function) veya iyileştirici seçme (pick).
    2.2 Bir eğitim döngüsü oluşturma.
3. Modeli veriye uydurma (fitting) ve bir tahmin yapma.
4. Modeli değerlendirme.
5. Deneysel olarak geliştirme (improve).
6. Eğitilen modeli kaydetme ve tekrar yükleme (reload).

## Alıştırmalar ve Faydalı Kaynaklar

Ek çalışmalar için __learnpytorch.io__ adresinden faydalanılabilir.

__https://github.com/mrdbourke/pytorch-deep-learning__ adresinden içerik ile ilgili etkileşime geçilebilir.

En önemli adres bu çalışmanın da üzerine tasarlandığı pytorch resmi adresi __pytorch.org__ adresi ve forum platformlarıdır.

Daha kolay şekilde Google Colab üzerinde PyTorch uygulamaları çalıştırabiliriz ya da yerel makinemizi de kullanabiliriz. Burada linux / ubuntu kullanılarak çalışmalar yerel bilgisayarımızda gerçekleştirilecektir.

Kullanacğımız kütüphaneleri aşağıda import edilmiştir.

In [ ]:
import torch # PyTorch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

CUDA, NVIDIA tarafından oluşturulan algoritmaların GPU üzerinde çalışmasını sağlayan teknolojidir. 

## PyTorch ile Tensor Yapılarına Giriş

#### Tensör Oluşturma

In [ ]:
# skaler (Basit bir değer.) bir tensör.
scalar = torch.tensor(7)
scalar

In [ ]:
print(type(scalar))

__torch.Tensor__, tek bir veri tipinin elemanlarını içeren çok boyutlu matristir.

Tensörün boyutu aşağıdaki gibi __ndim__ metotu ile alınabilir.

In [ ]:
scalar.ndim

In [ ]:
# Python int tipinde tensör'ü geri almak.
num = scalar.item()
print(num)
print(type(num))

In [ ]:
# vektör (Yönü olan sayısal büyüklük.) bir tensör.
vector = torch.tensor([3, 3])
vector

In [ ]:
print(type(vector)) # 7. satır ile aynı sonuç alınır.

In [ ]:
# Vektörün boyutu.
vector.ndim

__shape__ metotu ile de bilgi alınır.

In [ ]:
scalar.shape

In [ ]:
vector.shape

In [ ]:
# Matris olarak (2 x 2 şeklinde) bir tensör.
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX


In [ ]:
MATRIX.ndim

Kolay bir şekilde matris içindeki elemanlara ulaşabiliriz. Örneğin birinci satır ikinci sütundaki veriye aşağıdaki gibi ulaşırız.

In [ ]:
MATRIX[0][1]

Yine __shape__ metotu ile matris içindeki veri sayısına ulaşırız.

In [ ]:
MATRIX.shape

In [ ]:
# 3 Boyutlu bir tensör tanımı. 3 x 3 x 3 şeklinde olacak şekilde bir tanım.
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],
                        [[10, 11, 12],
                        [10, 11, 12],
                        [11, 12, 13]],
                        [[14, 15, 16],
                        [17, 18, 19],
                        [20, 21, 22]]])


In [ ]:
TENSOR.shape

In [ ]:
TENSOR.ndim

Örneğin 12 verisini yazdırmaya çalışalım.

In [ ]:
TENSOR[1][2][1] # 2. matris 3. satır 2. sutun olarak aldık.

Burada dikkat edilmesi gereken bir durum ise __skaler ve vektör değişken adlandırmaları küçük harf__ ile yapılırken __matris ve n-boyutlu tensör değişkenlerinin adlandırmaları ise büyük harfler__ ile yapılmaktadır.

## Rastgele (Random) Kullanılan Tensörler

Sinir ağlarında (neural networks) yapılan çalışmalar çok sayıda rastgele sayı içeren tensörleri, daha iyi veri temsillerini (represent) öğrenmek için doğru sayı verilerine ayarlamaktır.  

__Akış şu şekildedir;__

Rastgele sayılar --> Veri (Görüntü, metin vb. tensörleri.) --> Rastgele sayılar güncellenir. --> Veri --> Rastgele sayılar güncellenir.

__(2, 3) boyutunda rastgele bir tensör oluşturalım.__

Bunun için şu adresten faydalanılır: https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
rand_tensor = torch.rand(2, 3)

In [ ]:
rand_tensor

2 satır ve 3 sütundan oluşan rastgele bir tensör oluşturuldu. Tensörün boyutunu aşağıdaki gibi kontrol edebiliriz.

In [ ]:
rand_tensor.ndim

__3 boyutlu rastgele bir tensörü aşağıda oluşturalım.__

In [ ]:
rand_3d_tensor = torch.rand(2, 3, 4)

In [ ]:
rand_3d_tensor

Bu tensör ile ilgili bilgileri aşağıdaki gibi alabiliriz.

In [ ]:
rand_3d_tensor.ndim

In [ ]:
rand_3d_tensor.shape

__Bir görüntü(image) tensörüne benzer tensör oluşturalım. Bu tensör 3 boyutlu olmalıdır. Renk kanalları (R, G, B) , yükseklik (height), genişlik (width) değerlerinin büyüklükleri tensörün şeklini belirler.__

In [ ]:
rand_image_tensor = torch.rand(size=(3, 224, 224))

In [ ]:
rand_image_tensor.shape

In [ ]:
rand_image_tensor.ndim

## Sıfır ya da Birlerden Oluşan Tensörleri Oluşturmak

Makine öğrenmesi uygulamalarını oluşturmada bu şekilde olan tensörleri kullanmak, bunları değiştirmek ve geri döndürmek gerekebilir. Örneğin; bir görüntü verisi manipüle edilirken orijinal görüntüye dokunmadan bu verinin değerleri manipüle edilerek ilk başta sıfırlardan oluşan tensör içerisine kayıt edilir ve bu değer döndürülür.

__Sıfırlardan oluşan bir tensörü aşağıdaki gibi oluşturalım.__

In [ ]:
zeros_tensor = torch.zeros(size=(2, 3))
zeros_tensor

In [ ]:
zeros_tensor * rand_tensor # İki tensörün çarpımı.

__Birlerden oluşan tensörü aşağıdaki gibi oluşturalım.__

In [ ]:
ones_tensor = torch.ones(size=(2, 3))
ones_tensor

In [ ]:
ones_tensor * rand_tensor

Oluşan tensörlerin veri tiplerine aşağıdaki gibi bakabiliriz.

In [ ]:
ones_tensor.dtype

## Tensörleri Belirli Bir Aralıkta Oluşturmak

In [ ]:
torch.arange(0, 5)

In [ ]:
one_to_ten_tensor = torch.arange(1, 11)
one_to_ten_tensor

Tensör elemanları arasında adım aralığı aşağıdaki gibi eklenebilir.

In [ ]:
increased_tensor = torch.arange(start = 1, end = 1001, step = 125)
increased_tensor

__Burada dikkat edilmesi gereken end parametresi değerinin dahil edilmediğidir.__

__Belirli bir tensöre göre sıfırlardan oluşan tensörü oluşturalım.__

In [ ]:
tensor_zeros = torch.zeros_like(input = increased_tensor)
tensor_zeros

Aynı şekilde birlerden oluşan tensörü de oluşturalım.

In [ ]:
tensor_ones = torch.ones_like(input = increased_tensor)
tensor_ones

## Tensör Veri Tipleri

In [ ]:
# Float 32 veri tipinde tensör oluşturmak.
float_32_tensor = torch.tensor([1.0,2.0,3.0], dtype=None)

In [ ]:
float_32_tensor

In [ ]:
float_32_tensor.dtype

In [ ]:
# Float 16 veri tipinde tensör oluşturmak.
float_16_tensor = torch.tensor([4.0, 5.0, 6.0], dtype = torch.float16)

In [ ]:
float_16_tensor

In [ ]:
float_16_tensor.dtype  

Görüldüğü üzere bir tensör varsayılan olarak float 32 tipinde oluşturulur. 16, 32 vb. değerin hafızada tutulma uzunluğunu (detayını) belirten bit uzunluğudur. Daha ayrıntılı bilgi almak için şu adresi inceleyebiliriz: https://pytorch.org/docs/stable/tensors.html

Daha az yer kaplayan veriler ile daha hızlı hesaplama yapılabilir.

Tensör veri tipleri PyTorch ya da Derin öğrenme (deep learning) ile çalışırken karşılaşacağımız 3 ana hata başlıklarından biridir. Bu hatalar aşağıdaki gibi olabilir.

1. Tensors not right datatype --> Tensörler doğru veri tipinde değil.
2. Tensors not right shape --> Tensörler doğru şekilde değil.
3. Tensors not on the right device --> Tensörler doğru donanımda değil.

Tensörü oluştururken kullanılan diğer önemli iki parametre olan __device__ ve __required_grad__ aşağıdaki gibi tanımlanabilir.

In [ ]:
my_tensor = torch.tensor([1, 2, 3],
                         dtype = None,
                         device = "cuda", # Tensörün üzerinde oluşacağı donanım. (cuda, cpu vb.)
                         requires_grad = False) # Gradyanların kullanılması gerekiyor ise True geçilir.  

Float 32 tipinde bir tensörü aşağıdaki gibi float 16 tipinde bir tensöre çevirelim.

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16) # torch.half da yazılabilirdi.
float_16_tensor

Yukarıda da bahsettiğimiz gibi 16 ya da 32 bit uzunlukları verilerin hafızada tutulma uzunluğunu ya da detayını belirler. Bununla ilgili daha fazla bilgi almak için şu adrese bakabiliriz: https://en.wikipedia.org/wiki/Precision_(computer_science)

int tipinde bir tensör ile float tipinde bir tensörü aşağıdaki gibi çarpabiliriz.

In [ ]:
int_32_tensor = torch.tensor([1, 2, 3], dtype = torch.long)
int_32_tensor

In [ ]:
int_32_tensor * float_16_tensor

## Tensör Bilgilerini Almak

Bunlar yukarıda bahsedilen, aşağıda tekrar edilen hatalar için faydalıdır.

1. Tensors not right datatype --> Tensörler doğru veri tipinde değil. --> tensor.dtype
2. Tensors not right shape --> Tensörler doğru şekilde değil. --> tensor.shape
3. Tensors not on the right device --> Tensörler doğru donanımda değil. --> tensor.device

In [ ]:
one_tensor = torch.arange(1, 11, step = 2)
one_tensor

In [ ]:
# Tensör ile ilgili bazı bilgiler.
print(one_tensor)
print(f"Tensörün veri tipi: {one_tensor.dtype}")
print(f"Tensörün şekli: {one_tensor.shape}")
print(f"Tensör donanımı: {one_tensor.device}")

__Not:__ long veri tipi int64 tipine eşittir.

## Tensörleri Değiştirmek (Tensör Operasyonları)

Belirli işlemler aşağıdaki gibidir. Bir sinir ağı örüntüleri yakalamak için aşağıdaki işlemlerin bir kombinasyonu ile tensörleri optimize eder.

* Ekleme (Addition)
* Çıkarma (Subtraction)
* Çarpma (Multiplication)
* Bölme (Division)
* Matris Çarpımı  (Matrix Multiplication)

In [ ]:
# Tensöre (her bir elemanına) 15 ekleyelim.
tensor = torch.tensor([5, 6, 7])
tensor + 15

In [ ]:
# Tensörü (her bir elemanını) 10 ile çarpalım.
tensor * 10

In [ ]:
# Tensörden (her bir elemanından) 20 çıkarılım.
tensor - 10

Operatörler (+, -, *) yerine PyTorch içerisindeki fonksiyonları da kullanabiliriz. Aşağıdaki örnekleri inceleyelim.

In [ ]:
torch.add(tensor, 15)

In [ ]:
torch.mul(tensor, 10)

#### Matris Çarpımı (Matrix Multiplication) 

Derin öğrenme (deep learning) ve sinir ağlarında çarpımı (multiplication) aşağıdaki gibi iki şekilde ele alabiliriz. 

* Eleman tabanlı (element-wise) çarpım.
* Nokta çarpımı (dot production) ile matris çarpımı.

Detaylı bilgi için şu adrese bakabiliriz: https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [ ]:
# Eleman tabanlı yaklaşım.
print(tensor, " * ", tensor)
print(f"Eşittir: {tensor * tensor}")

In [ ]:
torch.matmul(tensor, tensor) # 5 * 5 + 6 * 6 + 7 * 7 = 110

Yukarıdaki işlem çarpım sonucu çıkan değerlerin toplamını vermektedir.

__Aşağıda yukarıda yaptığımız işlemlerin zaman açısından karşılaştırmasını yapalım.__

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

print(value)

In [ ]:
%%time
torch.matmul(tensor, tensor)

Görüldüğü üzere __PyTorch matmul__ fonksiyonu mikrosaniye seviyesinde çalışırken __for__ döngüsü ile yaptğımız sezgisel yaklaşım milisaniye seviyesinde daha yavaş çalışmaktadır. Çok daha fazla veriye sahip tensörlerde bu süre daha da uzayacaktır. Bu nedenle PyTorch bize performans yönünden de fayda sağlar.

## Matris Çarpımı (Matrix Multiplication) İkinci Kısım  

Matris çarpımında önemli iki ana kural vardır:
1. İç boyutlar (inner dimensions) eşleşmelidir. Yani (3, 2) @ (2, 3) ya da (5, 3) @ (3, 5) gibi bir çarpım olabilir. Burada @ matris çarpımı için kullanılacak sembollerden biridir. İç boyutlar ise 2 rakamlarıdır ve eşittir. 
2. Çarpım sonucu ortaya çıkan matrisin şekli dış boyutlardan oluşur. Örneğin (2, 3) @ (3, 2) sonucunda 2 x 2 şeklinde bir matris oluşur.

Örneğin; aşağıdaki matmul fonksiyonu hata verecektir. Çünkü iç boyutlar 2 ve 3 eşit değildir.

In [ ]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

Aşağıdaki çarpım ise 2 x 2 şeklinde matrisi verecek doğru bir çarpımdır.

In [ ]:
tensor_2_2 = torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

In [ ]:
tensor_2_2.shape

In [ ]:
tensor_2_2.ndim

## Matris Çarpımı (Matrix Multiplication) Üçüncü Kısım

__Derin öğrenmedeki yaygın hatalardan biri de şekil hatasıdır (shape error).__

In [ ]:
# Matris Çarpımında Şekil (Shape).
tensor_a = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

In [ ]:
tensor_a.shape # 3 x 2 şeklinde olan matrisin şekil bilgisinin doğrulanması.

In [ ]:
tensor_b = torch.tensor([[4, 5 , 6],
                         [7, 8, 9],
                         [10, 11, 12]])

In [ ]:
tensor_b.shape # 3 x 3 şeklinde olan matrisin şekil bilgisinin doğrulanması.

#### İki matrisi çarpmaya çalıştığımızda iç boyutlar eşit olmadığı için şekil hatasını (shape error) alırız. 

In [ ]:
# tensor_a @ tensor_b
## torch.matmul(tensor_a, tensor_b)
torch.mm(tensor_a, tensor_b) # matmul kısaltmasıdır.

#### Transpoz (transpose) işlemini kullanarak tensörleri değiştirir ve şekil hatalarını çözebiliriz.

Matris transpozu, verilen m x n şeklindeki matris tensörünün n x m şeklinde yazılmasıdır. Örnek uygulamayı aşağıda yapalım.

In [ ]:
tensor_a = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

In [ ]:
tensor_a, tensor_a.shape

In [ ]:
tensor_a.T, tensor_a.T.shape

Görüldüğü üzere 3 x 2 şeklindeki tensor_a matrisin transpozu alınarak 2 x 3 şeklindeki matrise çevirebildik. 

tensor_a'nın transpoz edilmiş tensörünü ve tensor_b tensörlerini aşağıdaki gibi çarpabilir, ek olarak şekil bilgisini alabiliriz.

In [ ]:
torch.mm(tensor_a.T, tensor_b), torch.mm(tensor_a.T, tensor_b).shape 

## Tensörlerde Toplam, Ortalama, Minumum ve Maksimum Değerleri Bulma ve Diğer İşlemler (Tensor Aggregation)

In [ ]:
# Bir tensör oluşturalım.
x_tensor = torch.arange(0, 20, 2)
x_tensor

In [ ]:
# Tensör içerisindeki minimum değeri iki farklı yol ile bulalım.
torch.min(x_tensor), x_tensor.min() 

In [ ]:
# Tensör içerisindeki maksimum değeri iki farklı yol ile bulalım.
torch.max(x_tensor), x_tensor.max()

#### Tensör ortalamasını bulalım.

Ortalama için Tensör veri tipi float olmalıdır. İlk olarak tensör veri tipine bakalım.

In [ ]:
x_tensor.dtype

int64(long) bilgisini aldık. Bu nedenle tensörü torch.mean() fonksiyonunun gerektirdiği üzere float tipinde belirterek ortalamayı aşağıdaki gibi iki farklı yol ile alırız.

In [ ]:
torch.mean(x_tensor.type(torch.float32)), x_tensor.type(torch.float32).mean()

In [ ]:
# Tensör toplamını iki farklı yol ile bulalım.
torch.sum(x_tensor), x_tensor.sum()

### Konumsal Minimum ve Maksimum Değerleri Bulma;

__argmin()__ ile tensör içerisindeki minimum değerin indeksi alınır.

In [ ]:
x_tensor = torch.arange(1, 11, step = 2)

In [ ]:
x_tensor

In [ ]:
x_tensor.argmin() # 1 değerinin indeksi 0.

__argmax()__ ile tensör içerisindeki maksimum değerin indeksi alınır.

In [ ]:
x_tensor.argmax() # 9 değerinin indeksi 4.

In [ ]:
x_tensor[0], x_tensor[4]

## Tensörleri Yeniden Şekillendirme (Reshaping), Görüntüleme (Viewing), İstifleme (Stacking), Sıkıştırma (Squeeze), Boyut ekleme (Unsquueze) ve Permute İşlemleri

1. Yeniden şekillendirme -bir tensörü başka şekile döndürme.
2. Görüntüleme - Orijinal tensörü hafızada tutmak üzere tensörün bir şekil ile yeniden döndürülmesi.
3. İstifleme - Üst üste ya da yan yana olacak şekilde tensörleri birleştirme.
4. Sıkıştırma - tensörden bir boyutu çıkarma.
5. Boyut ekleme - tensöre bir boyut ekleme.
6. Yeniden düzenleme (Permute) işlemi - belirli bir şekilde izin verilen boyutlar ile girişin (input) görüntüsünü döndürme.

#### Yeniden Şekillendirme

In [ ]:
# Bir tensör oluşturalım.
x = torch.arange(1., 10.)

In [ ]:
x

In [ ]:
x.shape

Bu tensörü aşağıdaki gibi 3 x 3 şeklinde 2 boyutlu hale getirebiliriz.

In [ ]:
x_reshaped = x.reshape(3, 3)
x_reshaped

In [ ]:
x_reshaped.ndim, x_reshaped.shape

#### Görüntüyü değiştirme (Orijinal tensörü değiştirmeden.)

In [ ]:
y = torch.arange(2., 22., step = 2)

In [ ]:
y, y.shape, y.ndim

In [ ]:
z = y.view(2, 5)
z, z.shape

Aşağıdaki işlem ile y tensörü verileri __view()__ ile iki boyutlu olarak z tensörü oluşturuldu. Burada __view__ içerisine geçilen parametrelerin  __y__ tensörü büyüklüğü ile uyumlu olduğuna ( 2 * 5 = 10) dikkat edilmelidir.

Burada dikkat edilmesi gereken ise z tensöründe yapılacak olan değişikliğin y tensörünü de değiştireceğidir. İki tensör aynı hafızayı (memory) paylaşırlar. Aşağıda bir örnek verilmiştir.

In [ ]:
z[:, 0] = 20
z, y

#### Tensörleri üst üste istifleme

In [ ]:
y, y.ndim, y.shape

In [ ]:
y_stacked = torch.stack([y, y, y, y], dim = 0)
y_stacked, y_stacked.ndim, y_stacked.shape

__dim__ parametresini __1__ olarak geçtiğimizde ise aşağıdaki gibi y tensörünün her bir verisi için bir satır oluşturarak 10 x 4 şeklinde bir tensör oluştururuz. 

In [ ]:
y_stacked_2 = torch.stack([y, y, y, y], dim = 1)
y_stacked_2, y_stacked_2.ndim, y_stacked_2.shape

#### Sıkıştırma işlemi (Squeeze)

In [ ]:
# Bir tensör oluşturalım.
x = torch.arange(1., 10.)

In [ ]:
x_reshaped = x.reshape(1, 9)

In [ ]:
x_reshaped, x_reshaped.shape

In [ ]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape

#### Print ile görselleştirme işlemi

In [ ]:
print(f"Önceki tensör: {x_reshaped}")
print(f"Önceki tensörün şekli: {x_reshaped.shape}")

# Tensörden bir boyutu çıkarma (sıkıştırma)
x_squeezed = x_reshaped.squeeze()
print(f"\nSıkıştırılmış tensör: {x_squeezed}")
print(f"Sıkıştırılmış tensörün şekli: {x_squeezed.shape}")

#### Boyut ekleme işleminin print ile görselleştirilmesi (Unsqueeze)

In [ ]:
print(f"Önceki tensör: {x_squeezed}")
print(f"Önceki tensör şekli: {x_squeezed.shape}")

#Tensöre bir boyut ekleme.
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f"\nYeni tensör: {x_unsqueezed}")
print(f"Yeni tensör şekli: {x_unsqueezed.shape}")

Kısaca bir önceki başlıktaki işlemin tersini yaparak boyut ekledik. __dim__ parametresi 0 geçildiği için 1 x 9 şeklinde bir tensör oluşturuldu. Parametre 1 olarak geçilseydi aşağıdaki gibi 9 x 1 şeklinde bir tensör oluşurdu.

In [ ]:
x_unsqueezed_2 = x_squeezed.unsqueeze(dim = 1)
print(f"\nYeni tensör: {x_unsqueezed_2}")
print(f"Yeni tensör şekli: {x_unsqueezed_2.shape}")

#### Yeniden Düzenleme (Permute) işlemi

__torch.permute()__ belirli bir sırada hedef bir tensörün boyutlarını yeniden düzenler. Aşağıda görüntü (image) verisi için bir örnek gösterilmiştir.

In [ ]:
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

In [ ]:
# Orijinal tensörü eksen (boyut) sırasına göre yeniden düzenleme (reaarranged).
x_permuted = x_original.permute(2, 0, 1) # 0 -> 1, 1 -> 2, 2 -> 0

In [ ]:
print(f"Önceki tensör şekli: {x_original.shape}") # [height, width, colour_channels]
print(f"Yeni tensör şekli: {x_permuted.shape}") # [colour_channels, height, width] 

Burada bir tensörde yapacağımız değişiklik diğer tensöre de yansır. Aşağıdaki bir örnekle doğrulayalım.

In [ ]:
x_original[0, 0, 0]

In [ ]:
x_original[0, 0, 0] = 6646
x_original[0, 0, 0], x_permuted[0, 0, 0]

## İndeksleme (Tensörden bir veri seçimi)

PyTorch'daki indeksleme NumPy dizisindekine benzer.

In [ ]:
# Bir tensör oluşturalım.
x_tensor = torch.arange(1, 10).reshape(1, 3, 3)

In [ ]:
x_tensor, x_tensor.shape, x_tensor.ndim

#### Aşağıdaki örneklerin anlaşılması önemlidir.

In [ ]:
x_tensor[0]

In [ ]:
x_tensor[0][0] # [1, 2, 3]

In [ ]:
x_tensor[0][0][2], x_tensor[0, 0, 2] # 3, 3

In [ ]:
# 7 verisini alalım.
x_tensor[0][2][0]

__':'__ tensörde bulunan boyutun tüm verilerini alır. Aşağıdaki örnekleri inceleyelim.

In [ ]:
x_tensor[0, :, 1] # 2, 5, 8

In [ ]:
x_tensor[0, 1, :] # 4, 5, 6

In [ ]:
# 0 ve 1. boyuttaki tüm verileri alırken 2. boyuttaki sadece 1. indeksi alalım.
x_tensor[:, :, 1] # 2, 5, 8

In [ ]:
# 0. boyuttaki tüm verileri alırken 1 ve 2. boyuttaki sadece 1. indeksteki verileri alalım.
x_tensor[:, 1, 1] # 5

In [ ]:
# 0 ve 1. boyuttaki 0. indeksi alırken 2. boyuttaki tüm veriler gelsin.
x_tensor[0, 0, :] # 1, 2, 3

In [ ]:
# 3, 6 ve 9 sonucunu alalım.
print(x_tensor[:, :, 2])

## PyTorch Tensörleri ve NumPy

NumPy Python tabanlı popüler sayısal işlemler kütüphanesidir. PyTorch ve NumPy birlikte kullanılır. 

NumPy dizi (array) yapılarını PyTorch tensörlerine çevirmemiz gerekebilir ya da tersi işlem yapılabilir.
1. NumPy verisi -> PyTorch Tensör - torch.from_numpy(ndarray)
2. PyTorch tensör -> NumPy verisi - torch.Tensor.numpy()

In [ ]:
import torch
import numpy as np

arr = np.arange(1.0, 10.0)
arr

In [ ]:
# NumPy dizisini (array) PyTorch tensörüne çevirme.
tensor = torch.from_numpy(arr)

In [ ]:
tensor, arr

Veri tipi bilgisini iki yapı için aşağıdaki gibi görüntüleriz. Dikkat edilmesi gereken varsayılan NumPy veri tipi __float64__ olarak verilir ve bu tensöre de yansır.

In [ ]:
tensor.dtype, arr.dtype

__NumPy verisinde bir değişiklik yaptığımızda bu tensörü etkilemeyecektir. Aşağıda bir örnek yapılmıştır.__

In [ ]:
arr = arr + 2
arr, tensor

In [ ]:
# PyTorch tensörü NumPy dizisine çevirme.
tensor = torch.ones(10)
tensor

In [ ]:
numpy_tensor = tensor.numpy()
numpy_tensor, numpy_tensor.dtype

Görüldüğü üzere tensörün varsayılan veri tipi __float32__ NumPy verisine de yansıdı.

#### Aynı hafızayı paylaşmadıkları için öncekine benzer olarak tensör verisinde yapılan değişiklik NumPy verisine yansımayacaktır.

In [ ]:
tensor = tensor + 1
numpy_tensor, tensor

## Yeniden Üretilebilirlik (Rastgele verilerden rastgele verilere bir döngü)

Bu, makine öğrenmesinde önemli bir konudur. Bir sinir ağı öğrenme işlemini şu şekilde yapar;

Rastgele veriler ile başla --> Tensör işlemleri --> Rastgele verileri güncelleme ve onların daha doğru veri temsilleri yapılmasının sağlanması --> bu işlemlerin tekrarı...

In [ ]:
torch.rand(2, 2) # Bu satırı her çalıştırmamızda farklı veriler ile tensör oluşur.

Sinir ağlarındaki rastgeleliği azaltma. PyTorch ile __random seed__ kavramı. Bu kavram sadece PyTorch özelinde olmayıp yapılan şey rastgeleliği tatlandırmadır(flavour). Daha iyi anlamak için aşağıda bir örnek yapalım.

In [ ]:
# Random iki tensör oluşturma.
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B) # False, False...

Yukarıdaki hücre her çalıştırmasında farklı rastgle tensörler verecektir. Aşağıda yine rastgele ancak yeniden üretilebilir tensörleri oluşturalım.

In [ ]:
# random seed kavramı.
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED) # Her tensörü oluşturmadan önce çalıştırılmalıdır.
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D) # True, True...

Yeniden üretilebilirlik için ek kaynak adresi: https://pytorch.org/docs/stable/notes/randomness.html - https://en.wikipedia.org/wiki/Random_seed

## PyTorch Üzerinde GPU Erişimine Farklı Yollar

Daha yüksek hesaplama için Tensörleri ve PyTorch nesnelerini GPU'lar üzerinde çalıştırma.

CUDA + NVIDIA + PyTorch ile GPU kullanarak daha hızlı hesaplama yapılabilir.

1. Ücretsiz GPU erişimi için Google Colab kullanılabilir. Google Colab'ın ücretli seçenekleri de mevcuttur. 
2. Kendi bilgisayarımızdaki GPU kullanılabilir. Bununla alakalı faydalı bir yazı adresi: https://timdettmers.com/2020/09/07/which-gpu-for-deep-learning/
3. Bulut bilişimi kullanmak: GCP, AWS ve Azure gibi servisler üzerindeki bilgisayarları kiralayarak onlara erişebiliriz. 

2 ve 3. seçenekler için ek olarak kurulum yapılması gerekmektedir. Bunun için PyTorch dokümantasyonundan yararlanılabilir. Adres: https://pytorch.org/get-started/locally/ 

__Not: Burada yapılan çalışmalar Ubuntu 20.04 yerel bilgisayar üzerinde yapılmıştır.__

In [1]:
!nvidia-smi # GPU bilgisi alınır.

Wed Nov 16 19:04:40 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.85.02    Driver Version: 510.85.02    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   32C    P0    N/A /  N/A |     10MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

PyTorch ile de GPU erişimini aşağıdaki gibi kontrol ederiz. CUDA NVIDIA tarafından bize sunulan sayısal hesaplama yapabilmek GPU programlama arayüzüdür.

In [3]:
import torch
torch.cuda.is_available()

True

PyTorch'un hem CPU hem de GPU üzerinde çalışabilmesinden dolayı cihaz seçimi için donanım agnostik kodunu (device agnostic code) ayarlama (setup) işlemi yapılabilir. Bunun için faydalı adres: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

Uygun ise GPU değil ise CPU çalışsın.

In [6]:
# Agnostik donanım kodunun ayarlanması.
device = "cuda" if torch.cuda.is_available() else "cpu"
device # BAsit şekilde, GPU erişimi yoksa CPU ayarlanır.

'cuda'

In [8]:
# Donanımların sayısını sayma. 
# Şu aşamada olmasa bile bu işlemler uygulama deneyimi arttıkça biz kullanıcılar tarafından kullanılır.
# Aynı uygulamada iki farklı model iki farklı GPU üzerinde çalışabilir.
torch.cuda.device_count()

1

## GPU ile Gerçek Deneyim: Tensörleri ya da Modelleri GPU Üzerine Yerleştirmek

Bunu istememizdeki neden daha hızlı sayısal hesaplamadır. 

In [12]:
# Bir tensör oluşturalım.
tensor = torch.tensor([1, 2, 3], device = "cpu")
# device parametresi girilmese bile varsayılan olarak cpu üzerinde çalışılır.

# GPU üzerinde çalışmayan, CPU üzerinde çalışan bir tensör.
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [13]:
# Uygunsa tensörü GPU üzerine alalım.
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

Tek bir GPU için cuda:0 sonucunu aldık.

## Tensörleri Tekrar CPU Üzerine Taşımak

Bir tensörü GPU üzerinde çalıştırırsak onu direkt olarak NumPy verisine dönüştüremeyiz.  Aşağıdaki komut donanım hatası verecektir.

In [14]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

Bu sorun aşağıdaki gibi ilgili tensörü cpu üzerine ayarlanarak çözülür.

In [18]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu 

array([1, 2, 3])

In [20]:
tensor_on_gpu # Bu tensör üzerinde değişiklik olmadığına dikkat edilmelidir.

tensor([1, 2, 3], device='cuda:0')

In [21]:
tensor_on_gpu[0] = 5
tensor_on_gpu

tensor([5, 2, 3], device='cuda:0')

tensor_on_gpu üzerindeki değişiklik cpu üzerindeki tensörü etkilemediği aşağıdaki gibi görülür.

In [23]:
tensor_back_on_cpu

array([1, 2, 3])

## Alıştırmalar ve Ek Müfredat

https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises adresindeki alıştırma __exercises__ klasörü içerisinde __00_pytorch_fundementals_exercise__ dosyası içerisinde çözülmüştür. Ayrıca bu adreste aşağıda da verilen ek kaynaklar verilmiştir. 

- https://pytorch.org/tutorials/beginner/basics/intro.html
- https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html
- https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html
- https://www.youtube.com/watch?v=f5liqUk0ZTw 