__PyTorch for Deep Learning in 2023: Zero To Mastery (Udemy) kaynağından çalışırken alınan notlardır.__

## PyTorch Nedir?

Popüler açık kaynak derin öğrenme / makine öğrenmesi çatısıdır (framework). GPU üzerinde çalışabilecek Python ile yazılmış derin öğrenme uygulamaları çalıştırabiliriz. Tesla, Microsoft, OpenAI gibi şirketler kullanır. 

## PyTorch Neden  Kullanılır?

Makine öğrenmesinin gücünden yararlanarak çok zor problemleri çözebilecek imkanı sağlar. Robotik, tarım, sağlık vb. birçok alanda PyTorch kullanılabilir. Bilgisayar görü, doğal dil işleme vb. birçok yaklaşım üzerinde çözüm sağlar. 

## GPU (Grafik İşlem Birimi) ve TPU (Tensör İşlem Birimi)

Yüksek işlem gücü isteyen derin öğrenme algoritmalarını GPU üzerinde çalıştırabiliriz. Burada NVIDIA tarafından sağlanan CUDA kullanılır.

TPU ise GPU'dan farklı olarak makine öğrenmesine özel amaçla geliştirilmiş bir yapıdır.

## Tensör Nedir?

Daha önceden bahsettiğimiz gibi sinir ağlarına çok çeşitli (görüntü, metin, ses vb.) veriler kendi hali ile değil nümerik halinde verilirler. Bu şekilde sinir ağlarının verileri sayısal giriş olarak aldığı ve yine sonucunda sonuç olarak ürettiği sayısal yapılara tensör denir. Tensörler vektör, matris vb. yapıda olabilirler.  

## Çalışma Akışı

1. Temel PyTorch bilgisi ve temelleri (tensör ve tensör operasyonları.)
2. Veri ön işleme (Tensörler üzerinde veriler.)
3. Önceden eğitilmiş derin öğrenme modellerini kullanma.
4. Veri ile model uydurma (fitting) (Örüntüleri öğrenme - learning patterns.)
5. Öğrenilen örüntüleri kullanarak bir model ile tahmin üretme.
6. Model tahminlerini değerlendirme (evaluating).
7. Modelleri kaydetme ve yükleme.
8. Özel (custom) veri üzerinde eğitilmiş bir model kullanarak tahmin yapma. 

## PyTorch Çalışma Akışı

1. Verileri hazırla (Tensörler ile ifade et.)
2. Önceden eğitilmiş bir model oluşturma veya seçme (build or pick.)
    2.1 Bir kayıp fonksiyonu (loss function) veya iyileştirici seçme (pick).
    2.2 Bir eğitim döngüsü oluşturma.
3. Modeli veriye uydurma (fitting) ve bir tahmin yapma.
4. Modeli değerlendirme.
5. Deneysel olarak geliştirme (improve).
6. Eğitilen modeli kaydetme ve tekrar yükleme (reload).

## Alıştırmalar ve Faydalı Kaynaklar

Ek çalışmalar için __learnpytorch.io__ adresinden faydalanılabilir.

__https://github.com/mrdbourke/pytorch-deep-learning__ adresinden içerik ile ilgili etkileşime geçilebilir.

En önemli adres bu çalışmanın da üzerine tasarlandığı pytorch resmi adresi __pytorch.org__ adresi ve forum platformlarıdır.

Daha kolay şekilde Google Colab üzerinde PyTorch uygulamaları çalıştırabiliriz ya da yerel makinemizi de kullanabiliriz. Burada linux / ubuntu kullanılarak çalışmalar yerel bilgisayarımızda gerçekleştirilecektir.

Kullanacğımız kütüphaneleri aşağıda import edilmiştir.

In [2]:
import torch # PyTorch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.0+cu117


CUDA, NVIDIA tarafından oluşturulan algoritmaların GPU üzerinde çalışmasını sağlayan teknolojidir. 

## PyTorch ile Tensor Yapılarına Giriş

#### Tensör Oluşturma

In [ ]:
# skaler (Basit bir değer.) bir tensör.
scalar = torch.tensor(7)
scalar

In [ ]:
print(type(scalar))

__torch.Tensor__, tek bir veri tipinin elemanlarını içeren çok boyutlu matristir.

Tensörün boyutu aşağıdaki gibi __ndim__ metotu ile alınabilir.

In [ ]:
scalar.ndim

In [ ]:
# Python int tipinde tensör'ü geri almak.
num = scalar.item()
print(num)
print(type(num))

In [ ]:
# vektör (Yönü olan sayısal büyüklük.) bir tensör.
vector = torch.tensor([3, 3])
vector

In [ ]:
print(type(vector)) # 7. satır ile aynı sonuç alınır.

In [ ]:
# Vektörün boyutu.
vector.ndim

__shape__ metotu ile de bilgi alınır.

In [ ]:
scalar.shape

In [ ]:
vector.shape

In [ ]:
# Matris olarak (2 x 2 şeklinde) bir tensör.
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX


In [ ]:
MATRIX.ndim

Kolay bir şekilde matris içindeki elemanlara ulaşabiliriz. Örneğin birinci satır ikinci sütundaki veriye aşağıdaki gibi ulaşırız.

In [ ]:
MATRIX[0][1]

Yine __shape__ metotu ile matris içindeki veri sayısına ulaşırız.

In [ ]:
MATRIX.shape

In [ ]:
# 3 Boyutlu bir tensör tanımı. 3 x 3 x 3 şeklinde olacak şekilde bir tanım.
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],
                        [[10, 11, 12],
                        [10, 11, 12],
                        [11, 12, 13]],
                        [[14, 15, 16],
                        [17, 18, 19],
                        [20, 21, 22]]])


In [ ]:
TENSOR.shape

In [ ]:
TENSOR.ndim

Örneğin 12 verisini yazdırmaya çalışalım.

In [ ]:
TENSOR[1][2][1] # 2. matris 3. satır 2. sutun olarak aldık.

Burada dikkat edilmesi gereken bir durum ise __skaler ve vektör değişken adlandırmaları küçük harf__ ile yapılırken __matris ve n-boyutlu tensör değişkenlerinin adlandırmaları ise büyük harfler__ ile yapılmaktadır.

## Rastgele (Random) Kullanılan Tensörler

Sinir ağlarında (neural networks) yapılan çalışmalar çok sayıda rastgele sayı içeren tensörleri, daha iyi veri temsillerini (represent) öğrenmek için doğru sayı verilerine ayarlamaktır.  

__Akış şu şekildedir;__

Rastgele sayılar --> Veri (Görüntü, metin vb. tensörleri.) --> Rastgele sayılar güncellenir. --> Veri --> Rastgele sayılar güncellenir.

__(2, 3) boyutunda rastgele bir tensör oluşturalım.__

Bunun için şu adresten faydalanılır: https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
rand_tensor = torch.rand(2, 3)

In [ ]:
rand_tensor

2 satır ve 3 sütundan oluşan rastgele bir tensör oluşturuldu. Tensörün boyutunu aşağıdaki gibi kontrol edebiliriz.

In [ ]:
rand_tensor.ndim

__3 boyutlu rastgele bir tensörü aşağıda oluşturalım.__

In [ ]:
rand_3d_tensor = torch.rand(2, 3, 4)

In [ ]:
rand_3d_tensor

Bu tensör ile ilgili bilgileri aşağıdaki gibi alabiliriz.

In [ ]:
rand_3d_tensor.ndim

In [ ]:
rand_3d_tensor.shape

__Bir görüntü(image) tensörüne benzer tensör oluşturalım. Bu tensör 3 boyutlu olmalıdır. Renk kanalları (R, G, B) , yükseklik (height), genişlik (width) değerlerinin büyüklükleri tensörün şeklini belirler.__

In [ ]:
rand_image_tensor = torch.rand(size=(3, 224, 224))

In [ ]:
rand_image_tensor.shape

In [ ]:
rand_image_tensor.ndim

## Sıfır ya da Birlerden Oluşan Tensörleri Oluşturmak

Makine öğrenmesi uygulamalarını oluşturmada bu şekilde olan tensörleri kullanmak, bunları değiştirmek ve geri döndürmek gerekebilir. Örneğin; bir görüntü verisi manipüle edilirken orijinal görüntüye dokunmadan bu verinin değerleri manipüle edilerek ilk başta sıfırlardan oluşan tensör içerisine kayıt edilir ve bu değer döndürülür.

__Sıfırlardan oluşan bir tensörü aşağıdaki gibi oluşturalım.__

In [ ]:
zeros_tensor = torch.zeros(size=(2, 3))
zeros_tensor

In [ ]:
zeros_tensor * rand_tensor # İki tensörün çarpımı.

__Birlerden oluşan tensörü aşağıdaki gibi oluşturalım.__

In [ ]:
ones_tensor = torch.ones(size=(2, 3))
ones_tensor

In [ ]:
ones_tensor * rand_tensor

Oluşan tensörlerin veri tiplerine aşağıdaki gibi bakabiliriz.

In [ ]:
ones_tensor.dtype

## Tensörleri Belirli Bir Aralıkta Oluşturmak

In [ ]:
torch.arange(0, 5)

In [ ]:
one_to_ten_tensor = torch.arange(1, 11)
one_to_ten_tensor

Tensör elemanları arasında adım aralığı aşağıdaki gibi eklenebilir.

In [ ]:
increased_tensor = torch.arange(start = 1, end = 1001, step = 125)
increased_tensor

__Burada dikkat edilmesi gereken end parametresi değerinin dahil edilmediğidir.__

__Belirli bir tensöre göre sıfırlardan oluşan tensörü oluşturalım.__

In [ ]:
tensor_zeros = torch.zeros_like(input = increased_tensor)
tensor_zeros

Aynı şekilde birlerden oluşan tensörü de oluşturalım.

In [ ]:
tensor_ones = torch.ones_like(input = increased_tensor)
tensor_ones

## Tensör Veri Tipleri

In [2]:
# Float 32 veri tipinde tensör oluşturmak.
float_32_tensor = torch.tensor([1.0,2.0,3.0], dtype=None)

In [3]:
float_32_tensor

tensor([1., 2., 3.])

In [4]:
float_32_tensor.dtype

torch.float32

In [5]:
# Float 16 veri tipinde tensör oluşturmak.
float_16_tensor = torch.tensor([4.0, 5.0, 6.0], dtype = torch.float16)

In [6]:
float_16_tensor

tensor([4., 5., 6.], dtype=torch.float16)

In [7]:
float_16_tensor.dtype  

torch.float16

Görüldüğü üzere bir tensör varsayılan olarak float 32 tipinde oluşturulur. 16, 32 vb. değerin hafızada tutulma uzunluğunu (detayını) belirten bit uzunluğudur. Daha ayrıntılı bilgi almak için şu adresi inceleyebiliriz: https://pytorch.org/docs/stable/tensors.html

Daha az yer kaplayan veriler ile daha hızlı hesaplama yapılabilir.

Tensör veri tipleri PyTorch ya da Derin öğrenme (deep learning) ile çalışırken karşılaşacağımız 3 ana hata başlıklarından biridir. Bu hatalar aşağıdaki gibi olabilir.

1. Tensors not right datatype --> Tensörler doğru veri tipinde değil.
2. Tensors not right shape --> Tensörler doğru şekilde değil.
3. Tensors not on the right device --> Tensörler doğru donanımda değil.

Tensörü oluştururken kullanılan diğer önemli iki parametre olan __device__ ve __required_grad__ aşağıdaki gibi tanımlanabilir.

In [13]:
my_tensor = torch.tensor([1, 2, 3],
                         dtype = None,
                         device = "cuda", # Tensörün üzerinde oluşacağı donanım. (cuda, cpu vb.)
                         requires_grad = False) # Gradyanların kullanılması gerekiyor ise True geçilir.  

Float 32 tipinde bir tensörü aşağıdaki gibi float 16 tipinde bir tensöre çevirelim.

In [14]:
float_16_tensor = float_32_tensor.type(torch.float16) # torch.half da yazılabilirdi.
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

Yukarıda da bahsettiğimiz gibi 16 ya da 32 bit uzunlukları verilerin hafızada tutulma uzunluğunu ya da detayını belirler. Bununla ilgili daha fazla bilgi almak için şu adrese bakabiliriz: https://en.wikipedia.org/wiki/Precision_(computer_science)

int tipinde bir tensör ile float tipinde bir tensörü aşağıdaki gibi çarpabiliriz.

In [15]:
int_32_tensor = torch.tensor([1, 2, 3], dtype = torch.long)
int_32_tensor

tensor([1, 2, 3])

In [16]:
int_32_tensor * float_16_tensor

tensor([1., 4., 9.], dtype=torch.float16)

## Tensör Bilgilerini Almak

Bunlar yukarıda bahsedilen, aşağıda tekrar edilen hatalar için faydalıdır.

1. Tensors not right datatype --> Tensörler doğru veri tipinde değil. --> tensor.dtype
2. Tensors not right shape --> Tensörler doğru şekilde değil. --> tensor.shape
3. Tensors not on the right device --> Tensörler doğru donanımda değil. --> tensor.device

In [18]:
one_tensor = torch.arange(1, 11, step = 2)
one_tensor

tensor([1, 3, 5, 7, 9])

In [21]:
# Tensör ile ilgili bazı bilgiler.
print(one_tensor)
print(f"Tensörün veri tipi: {one_tensor.dtype}")
print(f"Tensörün şekli: {one_tensor.shape}")
print(f"Tensör donanımı: {one_tensor.device}")

tensor([1, 3, 5, 7, 9])
Tensörün veri tipi: torch.int64
Tensörün şekli: torch.Size([5])
Tensör donanımı: cpu


__Not:__ long veri tipi int64 tipine eşittir.

## Tensörleri Değiştirmek (Tensör Operasyonları)

Belirli işlemler aşağıdaki gibidir. Bir sinir ağı örüntüleri yakalamak için aşağıdaki işlemlerin bir kombinasyonu ile tensörleri optimize eder.

* Ekleme (Addition)
* Çıkarma (Subtraction)
* Çarpma (Multiplication)
* Bölme (Division)
* Matris Çarpımı  (Matrix Multiplication)

In [4]:
# Tensöre (her bir elemanına) 15 ekleyelim.
tensor = torch.tensor([5, 6, 7])
tensor + 15

tensor([20, 21, 22])

In [5]:
# Tensörü (her bir elemanını) 10 ile çarpalım.
tensor * 10

tensor([50, 60, 70])

In [6]:
# Tensörden (her bir elemanından) 20 çıkarılım.
tensor - 10

tensor([-5, -4, -3])

Operatörler (+, -, *) yerine PyTorch içerisindeki fonksiyonları da kullanabiliriz. Aşağıdaki örnekleri inceleyelim.

In [8]:
torch.add(tensor, 15)

tensor([20, 21, 22])

In [13]:
torch.mul(tensor, 10)

tensor([50, 60, 70])

#### Matris Çarpımı (Matrix Multiplication) 

Derin öğrenme (deep learning) ve sinir ağlarında çarpımı (multiplication) aşağıdaki gibi iki şekilde ele alabiliriz. 

* Eleman tabanlı (element-wise) çarpım.
* Nokta çarpımı (dot production) ile matris çarpımı.

Detaylı bilgi için şu adrese bakabiliriz: https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [15]:
# Eleman tabanlı yaklaşım.
print(tensor, " * ", tensor)
print(f"Eşittir: {tensor * tensor}")

tensor([5, 6, 7])  *  tensor([5, 6, 7])
Eşittir: tensor([25, 36, 49])


In [17]:
torch.matmul(tensor, tensor) # 5 * 5 + 6 * 6 + 7 * 7 = 110

tensor(110)

Yukarıdaki işlem çarpım sonucu çıkan değerlerin toplamını vermektedir.

__Aşağıda yukarıda yaptığımız işlemlerin zaman açısından karşılaştırmasını yapalım.__

In [18]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

print(value)

tensor(110)
CPU times: user 1.95 ms, sys: 255 µs, total: 2.21 ms
Wall time: 8.03 ms


In [19]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 747 µs, sys: 0 ns, total: 747 µs
Wall time: 451 µs


tensor(110)

Görüldüğü üzere __PyTorch matmul__ fonksiyonu mikrosaniye seviyesinde yaparken __for__ döngüsü ile yaptğımız sezgisel yaklaşım çok milisaniye seviyesinde daha yavaş çalışmaktadır. Çok daha fazla veriye sahip tensörlerde bu süre daha da uzayacaktır. Bu nedenle PyTorch bize performans yönünden de fayda sağlar.